### PR TITLE
let's remove json schema out of merry

### LINKED ISSUE #82: move json-schema-middleware out of merry
should have this as its own package and possibly send this out in our next major release.

this sort brings the question whether our error and parse wrappers should be their own thing and just bring them into merry instead? hmm hmmm hmmmm

### PR DESCRIPTION
**Pull request by lrlna**
This moves it out of merry's core + mentions a reference to the newly created
[json-schema-middleware](https://github.com/shipharbor/json-schema-middleware) package. This also a breaking change. 

a solution to close #82

### CODE REVIEW

**Comment by lrlna** [comment]
hmmmm didn't think `gateway` was using schema stuff too; i'll look into fixing that tom morn o.O

**Comment by yoshuawuyts** [comment]
amaze! :D

**Comment by lrlna** [comment]
woops i forgot on tuesday; but fixed nowwwww :D

**Comment by lrlna** [comment]
no longer a thing, yo

**Pull request closed without merging**
